### model
model_name_or_path: "" # Qwen2.5-Coder-7B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
report_to: tensorboard
logging_dir: ./log_output/train-7b
finetuning_type: full
flash_attn: fa2

### dataset
dataset_dir: "" 
dataset: sqlflow
template: qwen
cutoff_len: 4096      
max_samples: null    
overwrite_cache: true 
preprocessing_num_workers: 8 
dataloader_num_workers: 8

### output
output_dir: ./ckpts/train-7b-synsql-1
logging_steps: 50
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
deepspeed: "" # use ds_z2_config.json
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-5    
num_train_epochs: 2       
max_grad_norm: 0.5       
lr_scheduler_type: cosine
warmup_ratio: 0.15
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500  